name = "brouwerijindenacht-nl"
compatibility_date = "2024-09-20"

[site]
bucket = "./"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js", "**/*.json", "**/*.xml", "**/*.txt"]
fallthrough = true

[[build.upload.rules]]
type = "Binary"
globs = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.svg", "**/*.ico", "**/*.webp"]